version: "3.7"
services:
  db:
    image: postgres:14.1
    container_name: lucksheet_postgres
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgresql/data:/var/lib/postgresql/data/pgdata
  redis:
    image: redis:6.2.6
    container_name: lucksheet_redis
    ports:
      - "6379:6379"